name: Vivat ETL

on:
  schedule:
    - cron: '0 6 * * *'  # runs every day at 6:00 AM UTC
  workflow_dispatch:     # manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run parser
      run: python etl/parser.py

    - name: Commit updated DB
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        if git diff --quiet db/books_links.sqlite3; then
          echo "No changes to commit."
        else
          git add db/books_links.sqlite3
          git commit -m "Update raw_links DB"
          git push
        fi
