name: Vivat ETL

on:
  schedule:
    - cron: '0 6 * * *'  # runs every day at 6:00 AM UTC
  workflow_dispatch:     # manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run parser
      run: python etl/parser.py
      
    - name: Commit updated DB if hash changed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    
        echo "🔍 Проверка хэшей:"
        OLD_HASH=$(git show HEAD:db/books_links.sqlite3 2>/dev/null | sha256sum | awk '{print $1}')
        NEW_HASH=$(sha256sum db/books_links.sqlite3 | awk '{print $1}')
    
        echo "OLD_HASH: $OLD_HASH"
        echo "NEW_HASH: $NEW_HASH"
    
        if [ "$OLD_HASH" = "$NEW_HASH" ]; then
          echo "✅ No changes to commit."
        else
          echo "📦 Changes detected, committing..."
          git add db/books_links.sqlite3
          git commit -m "Update raw_links DB"
          git push
        fi
